import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight } from 'lucide-react';
import { projects } from '@/lib/content';
import KineticHeading from './KineticHeading';
import SplitChars from './SplitChars';
// Home-only card names, as edited on the Claude Design canvas. The projects pages keep the concept names.
const homeCards=[{title:'TIME SERVICE PROFILES',category:'Professional Experience'},{title:'Wooden Stands',category:'Brand experience'},{title:'Systems & Pavilions',category:'Exhibition design'},{title:'Event Organizer',category:'Event production'},{title:'Displays Stores',category:'Creative Branding'},{title:'Vehicles & Tour',category:'Service Journey'}];
export function ProjectCard({project,index,bento=false}:{project:typeof projects[number];index:number;bento?:boolean}){return <Link href={`/projects/${project.slug}/`} className={`project-card ${bento?'bento-card':''}`} data-tilt><div className="project-image"><Image src={`/images/${project.image}.jpg`} alt={`${project.title} — AI-generated ${project.category.toLowerCase()} concept`} fill sizes={bento?'(max-width:640px) 92vw, (max-width:1000px) 45vw, 60vw':'(max-width:640px) 92vw, (max-width:1000px) 45vw, 31vw'}/><span className="project-tag">CONCEPT {String(index+1).padStart(2,'0')}</span><span className="project-open"><ArrowUpRight size={24}/><span>Explore concept</span></span></div><div className="project-meta"><div><SplitChars as="h3" variant="reveal" lines={[project.title]} delay={.2+(index%3)*.1} stagger={.022}/><p>{project.category}</p></div><span className="project-arrow"><ArrowUpRight size={22}/></span></div></Link>;}
export default function Projects(){return <section id="projects" className="section projects-section"><div className="section-heading"><div><p className="eyebrow"><span/> OUR PROJECTS / DESIGN EXPLORATIONS</p><KineticHeading first="Spaces that" second="make an impression"/></div><div className="section-intro"><p className="thai">เมื่อแนวคิด กลายเป็นพื้นที่แห่งความเป็นไปได้</p><p>A collection of spatial concepts.<br/>Designed to spark your next idea.</p><Link href="/projects/" className="text-link">View the collection <ArrowUpRight size={17}/></Link></div></div><div className="project-grid project-bento">{projects.map((p,i)=><ProjectCard key={p.slug} project={{...p,...homeCards[i]}} index={i} bento/>)}</div></section>;}
